[project]
name = "dream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "albumentations",
    "flax>=0.12.7",
    "future",
    "gdown>=6.0.0",
    "grain>=0.2.16",
    "jax>=0.10.0",
    "matplotlib",
    "numpy>=2.4.4",
    "opencv-python",
    "pandas",
    "pillow",
    "pyrr",
    "pytest",
    "rich>=15.0.0",
    "ruamel-yaml>=0.19.1",
    "scipy",
    "seaborn",
    "tensorboardx",
    "torch==2.9.0",
    "torchvision==0.24.0",
    "tqdm",
    "tyro>=1.0.13",
    "wandb",
    "webcolors",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["dream*"]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
